services:
  jekyll:
    image: jekyll/jekyll:latest
    ports:
      - "8080:4000"
    volumes:
      - .:/srv/jekyll
    command: >
      sh -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload-port 35729 --force_polling"
    environment:
      - JEKYLL_ENV=development

